language: node_js
node_js:
  - "12"

services:
  - docker

before_deploy:
  - script/setup_helm.sh
  - script/setup_aws.sh $AWS_ACCESS_KEY $AWS_SECRET $AWS_REIGON $CLUSTER_NAME

deploy:
  - provider: script
    script: bash scripts/publish_dockerhub.sh $TRAVIS_TAG && scripts/deploy.sh $TRAVIS_TAG staging
    on:
      tags: true
      branch: master
  - provider: script
    script: bash scripts/publish_dockerhub.sh $TRAVIS_TAG && scripts/deploy.sh $TRAVIS_TAG  dev
    on:
      tags: true
      branch: dev

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL