language: node_js
node_js:
  - "14"

cache:
  npm: false
  yarn: true

env:
  global:
    - MYSQL_DATABASE=xr3ngine
    - MYSQL_USER=root
    - MYSQL_PASSWORD=

services:
  - docker
  - mysql

before_script:
  - mysql -e 'CREATE DATABASE xr3ngine;'

jobs:
  include:
    - stage: install
      script: yarn install
    - stage: lint
      script: yarn lint
    - stage: build-docker
      script yarn build-docker

before_deploy:
  - scripts/setup_helm.sh
  - scripts/setup_aws.sh $AWS_ACCESS_KEY $AWS_SECRET $AWS_REGION $CLUSTER_NAME

deploy:
#  - provider: script
#    script: bash scripts/publish_dockerhub.sh staging $TRAVIS_COMMIT xr3ngine/xr3ngine && scripts/deploy.sh staging $TRAVIS_COMMIT
#    on:
#      branch: master
  - provider: script
    script: bash scripts/publish_dockerhub.sh dev $TRAVIS_COMMIT xr3ngine/xr3ngine && scripts/deploy.sh dev $TRAVIS_COMMIT
    on:
      branch: dev
  - provider: script
    script: bash scripts/publish_dockerhub.sh latest $TRAVIS_TAG xr3ngine/xr3ngine
    on:
      tags: true
      all_branches: true

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
