language: node_js
node_js:
  - "14"
cache:
  npm: false
  yarn: true
  directories:
    - "node_modules"
env:
  global:
    - MYSQL_DATABASE=xr3ngine
    - MYSQL_USER=root
    - MYSQL_PASSWORD=
services:
  - docker
  - mysql
jobs:
  include:
    - stage: compile
      script:
      - yarn install
      - yarn lint
      - yarn build-docker
      if: branch != dev
#    - stage: staging-deploy
#      script: bash scripts/publish_dockerhub.sh staging $TRAVIS_COMMIT xr3ngine/xr3ngine && scripts/deploy.sh staging $TRAVIS_COMMIT
#      on:
#        branch: master
    - stage: dev-deploy
      script:
        - scripts/setup_helm.sh
        - scripts/setup_aws.sh $AWS_ACCESS_KEY $AWS_SECRET $AWS_REGION $CLUSTER_NAME
        - bash scripts/publish_dockerhub.sh dev $TRAVIS_COMMIT xr3ngine/xr3ngine && scripts/deploy.sh dev $TRAVIS_COMMIT
      if: branch = dev
#    - stage: tag-deploy
#      script: bash scripts/publish_dockerhub.sh latest $TRAVIS_TAG xr3ngine/xr3ngine
#      on:
#        tags: true
#        all_branches: true
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
sudo: required
install:
  - sudo apt-get install -y ccrypt
  - echo $DOCKER_HUB_PASSWORD > info.txt
  - ccencrypt info.txt -K $KNOWN_SECRET
  - cat info.txt.cpt | base64