{{- if .Values.api.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "xrengine.api.fullname" . }}
  labels:
    {{- include "xrengine.api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.port }}
      protocol: TCP
      name: http
    {{ if .Values.api.service.corsServerPort }}
    - port: {{  .Values.api.service.corsServerPort }}
      targetPort: {{ .Values.api.service.corsServerPort }}
      protocol: TCP
      name: cors-proxy
    {{ end }}
  selector:
    {{- include "xrengine.api.selectorLabels" . | nindent 4 }}
{{- end -}}
