{{- if .Values.api.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "xrsocial.api.fullname" . }}
  labels:
    {{- include "xrsocial.api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "xrsocial.api.selectorLabels" . | nindent 4 }}
{{- end -}}
