{{- if .Values.client.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "xrsocial.client.fullname" . }}
  labels:
    {{- include "xrsocial.client.labels" . | nindent 4 }}
spec:
  type: {{ .Values.client.service.type }}
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: {{ .Values.client.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "xrsocial.client.selectorLabels" . | nindent 4 }}
{{- end -}}
