{{- if and .Values.client.enabled .Values.client.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "xrsocial.client.serviceAccountName" . }}
  labels:
    {{- include "xrsocial.client.labels" . | nindent 4 }}
  {{- with .Values.client.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
