{{- if .Values.api.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "xr3ngine.gameserver.fullname" . }}
  labels:
    {{- include "xr3ngine.gameserver.labels" . | nindent 4 }}
data:
{{- if .Values.gameserver.extraEnv }}
{{ toYaml .Values.gameserver.extraEnv | indent 2 }}
{{- end }}
{{- if .Values.gameserver.config }}
  NODE_CONFIG: '{{ mustToJson .Values.gameserver.config }}'
{{- end }}
{{- end -}}
