{{- if and .Values.media.enabled .Values.media.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "xr3ngine.media.serviceAccountName" . }}
  labels:
    {{- include "xr3ngine.media.labels" . | nindent 4 }}
  {{- with .Values.media.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
