{{- if .Values.media.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xrsocial.media.fullname" . }}
  labels:
    {{- include "xrsocial.media.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.media.replicaCount }}
  selector:
    matchLabels:
      {{- include "xrsocial.media.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "xrsocial.media.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/media-server-configmap.yaml") . | sha256sum }}
    spec:
    {{- with .Values.media.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "xrsocial.media.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.media.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.media.securityContext | nindent 12 }}
          image: "{{ .Values.media.image.repository }}:{{ .Values.media.image.tag }}"
          imagePullPolicy: {{ .Values.media.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "xrsocial.media.fullname" . }}
                optional: true
            - configMapRef:
                name: {{ include "xrsocial.api.fullname" . }}
                optional: true
          env:
            - name: SERVER_MODE
              value: "media"
            - name: KUBERNETES
              value: "true"
            - name: MYSQL_USER
              value: {{ .Values.mariadb.db.user }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mariadb.db.name }}
            - name: MYSQL_PASSWORD
              {{- if not .Values.mariadb.enabled }}
              value: {{ .Values.mariadb.db.password }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  {{- if .Values.mariadb.existingSecret }}
                  name: {{ .Values.mariadb.existingSecret }}
                  {{- else }}
                  name: {{ template "xrsocial.mariadb.fullname" . }}
                  {{- end }} 
                  key: mariadb-password
              {{- end }}
            - name: MYSQL_HOST
              value: {{ template "xrsocial.mariadb.host" . }}
          ports:
            - name: http
              containerPort: 3030
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
          resources:
            {{- toYaml .Values.media.resources | nindent 12 }}
      {{- with .Values.media.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.media.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.media.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
