{{- if .Values.spoke.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "xr3ngine.spoke.fullname" . }}
  labels:
    {{- include "xr3ngine.spoke.labels" . | nindent 4 }}
spec:
  type: {{ .Values.spoke.service.type }}
  ports:
    - port: {{ .Values.spoke.service.port }}
      targetPort: {{ .Values.spoke.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "xr3ngine.spoke.selectorLabels" . | nindent 4 }}
{{- end }}
