{{- if and .Values.spoke.enabled .Values.spoke.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "xrsocial.spoke.serviceAccountName" . }}
  labels:
    {{- include "xrsocial.spoke.labels" . | nindent 4 }}
  {{- with .Values.spoke.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
