{{- if .Values.api.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "xr3ngine.api.fullname" . }}
  labels:
    {{- include "xr3ngine.api.labels" . | nindent 4 }}
data:
{{- if .Values.api.extraEnv }}
{{ toYaml .Values.api.extraEnv | indent 2 }}
{{- end }}
{{- if .Values.api.config }}
  NODE_CONFIG: '{{ mustToJson .Values.api.config }}'
{{- end }}
{{- end -}}
