{{- if .Values.client.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "xr3ngine.client.fullname" . }}
  labels:
    {{- include "xr3ngine.client.labels" . | nindent 4 }}
data:
{{- if .Values.client.extraEnv }}
{{ toYaml .Values.client.extraEnv | indent 2 }}
{{- end }}
{{- if .Values.client.config }}
  NODE_CONFIG: '{{ mustToJson .Values.client.config }}'
{{- end }}
{{- end }}
