{{- if and .Values.gameserver.enabled .Values.gameserver.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "xr3ngine.gameserver.serviceAccountName" . }}
  labels:
    {{- include "xr3ngine.gameserver.labels" . | nindent 4 }}
    {{- with .Values.gameserver.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
