{{- if .Values.editor.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "xr3ngine.editor.fullname" . }}
  labels:
    {{- include "xr3ngine.editor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.editor.service.type }}
  ports:
    - port: {{ .Values.editor.service.port }}
      targetPort: {{ .Values.editor.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "xr3ngine.editor.selectorLabels" . | nindent 4 }}
{{- end }}
