
version: '2.3'
services:
  db:
    image: mariadb:10.4
    container_name: xr3ngine_db
    environment:
      MYSQL_ROOT_PASSWORD: xr3ngine-root-pa$$w0rd
      MYSQL_DATABASE: xr3ngine
      MYSQL_USER: server
      MYSQL_PASSWORD: password
    ports:
      - '3307:3306'
    