
version: '2.3'
services:
  db:
    image: mariadb:10.4
    container_name: xrchat_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: xrchatrootpa$$w0rd
      MYSQL_DATABASE: xrchat
      MYSQL_USER: server
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'