{{- if .Values.bot.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "xr3ngine-bot.bot.fullname" . }}
  labels:
    {{- include "xr3ngine-bot.bot.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - events
      - services
      - configmaps
      - endpoints
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
{{- end }}
