{{- if and .Values.bot.enabled .Values.bot.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bot.serviceAccountName" . }}
  labels:
    {{- include "bot.labels" . | nindent 4 }}
    {{- with .Values.bot.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
