apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: xr3ngine
resources:
  - xr3ngine.yaml
secretGenerator:
  - name: xr3ngine-dev-secrets
    env: xr3ngine-dev-secrets.env
generatorOptions:
  disableNameSuffixHash: true