name: workflow
on:
  push:
    branches-ignore:
      - dev
      - master
jobs:
  compile-codebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn install
      - run: yarn lint
      - run: yarn build-docker