name: dev-deploy
on:
  push:
    branches:
      [dev]
jobs:
  dev-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Setup Helm
        run: scripts/setup_helm.sh
      - name: Setup AWS
        run: scripts/setup_aws.sh $AWS_ACCESS_KEY $AWS_SECRET $AWS_REGION $CLUSTER_NAME
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET: ${{ secrets.AWS_SECRET }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
      - name: Space debug
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - run: echo ${{ secrets.DOCKER_LABEL }} | sed -e 's/\(.\)/\1 /g'
      - run: echo ${{ secrets.REPO_NAME }} | sed -e 's/\(.\)/\1 /g'
      - run: echo ${{ secrets.AWS_REGION }} | sed -e 's/\(.\)/\1 /g'
      - run: echo ${{ secrets.ECR_URL }} | sed -e 's/\(.\)/\1 /g'
      - name: Build Docker Image
        run: bash scripts/build_docker.sh dev $DOCKER_LABEL $AWS_REGION
        env:
          DOCKER_LABEL: ${{ secrets.DOCKER_LABEL }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_URL: ${{ secrets.ECR_URL }}
      - name: npm-install 'cli' and 'aws-sdk'
	@@ -44,8 +40,29 @@ jobs:
        run: bash scripts/publish_ecr.sh dev $GITHUB_SHA $DOCKER_LABEL $AWS_REGION
        env:
          DOCKER_LABEL: ${{ secrets.DOCKER_LABEL }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_URL: ${{ secrets.ECR_URL }}
      - name: Deploy to EKS
        run: bash scripts/deploy.sh dev $GITHUB_SHA