name: documentation

on:
  pull_request:
    branches: [dev]
  push:
    branches: [dev]

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Test Build
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |
          npm install --production=false --legacy-peer-deps
          cd packages/docs
          npm install --production=false --legacy-peer-deps
          npm run build
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: Release to GitHub Pages
        env:
          NODE_OPTIONS: --max_old_space_size=8192
          USE_SSH: true
          GIT_USER: git
          DEPLOYMENT_BRANCH: master
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "gh-actions"
          npm install --production=false --legacy-peer-deps
          cd packages/docs
          npm install --production=false --legacy-peer-deps
          npm run deploy
