name: publish-npm

on:
  release:
    types: [ created ]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https://npm.pkg.github.com/
          scope: '@XRFoundation'
#      - run: npm i
      - run: git config user.name xrengine-ci
      - run: git config user.email ci-bot@xrengine.io
      - run: echo lerna_version=$(node -p 'require("./lerna.json").version') >> $GITHUB_ENV
      - run: git switch -c version-increment-${{ github.event.release.tag_name }}
      - run: npm run version-increment-no-tag ${{ github.event.release.tag_name }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: npm run version-increment-no-tag
        if: ${{ github.event.release.tag_name == '' }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: git add .
      - run: git commit -m ${{ github.event.release.tag_name }}
      - run: git push origin ${{ github.event.release.tag_name }}
      - uses: peter-evans/create-pull-request@v3
        with:
          committer: ci-bot@xrengine.io
          title: v${{ github.event.release.tag_name }}
          body: Bump version to v${{ github.event.release.tag_name }}
          delete-branch: true
          branch: ${{ github.event.release.tag_name }}
      - run: npm run publish-no-verify
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm run update-name-gh-package
      - run: git add .
      - run: git commit -m 'GH Packages'
      - run: npm run publish-github
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}