name: publish-npm

on:
  release:
    types: [ created ]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https://npm.pkg.github.com/
          scope: '@XRFoundation'
#      - run: npm i
      - run: git config user.name "CI Bot"
      - run: git config user.email ci-bot@xrengine.io
      - run: echo pr_branch_name=version-increment-${{ github.event.release.tag_name }} >> $GITHUB_ENV
      - run: git switch -c ${{ env.pr_branch_name }}
      - run: npm run version-increment-no-tag ${{ github.event.release.tag_name }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: npm run version-increment-no-tag
        if: ${{ github.event.release.tag_name == '' }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: git add .
      - run: git commit -m ${{ github.event.release.tag_name }}
      - run: git log
      - run: git push --no-verify origin ${{ env.pr_branch_name }}
      - run: echo "PR Branch name:" ${{ env.pr_branch_name }}
      - run: echo "Target Commitish:" ${{ github.event.release.target_commitish }}
      - uses: repo-sync/pull-request@v2
        with:
          destination_branch: ${{ github.event.release.target_commitish }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: ${{ env.pr_branch_name }}
          pr_title: ${{ github.event.release.tag_name }}
          pr_body: Bump version to ${{ github.event.release.tag_name }}
      - run: npm run publish-no-verify
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm run update-name-gh-package
      - run: git add .
      - run: git commit -m 'GH Packages'
      - run: npm run publish-github
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}