name: publish-npm

on:
  release:
    types: [ created ]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https://npm.pkg.github.com/
          scope: '@XRFoundation'
#      - run: npm i
      - run: git config user.name CI Bot
      - run: git config user.email ci-bot@xrengine.io
      - run: echo pr_branch_name=version-increment-${{ github.event.release.tag_name }} >> $GITHUB_ENV
      - run: git switch -c ${{ env.pr_branch_name }}
      - run: npm run version-increment-no-tag ${{ github.event.release.tag_name }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: npm run version-increment-no-tag
        if: ${{ github.event.release.tag_name == '' }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: git add .
      - run: git commit -m ${{ github.event.release.tag_name }}
      - run: git push --no-verify origin ${{ env.pr_branch_name }}
      - uses: peter-evans/create-pull-request@v3
        with:
          committer: CI Bot <ci-bot@xrengine.io>
          title: v${{ github.event.release.tag_name }}
          body: Bump version to v${{ github.event.release.tag_name }}
          delete-branch: true
          branch: ${{ env.pr_branch_name }}
          base: ${{ github.event.release.target_commitish }}
      - run: npm run publish-no-verify
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm run update-name-gh-package
      - run: git add .
      - run: git commit -m 'GH Packages'
      - run: npm run publish-github
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}