name: update-deps-branch
on:
  push:
    branches:
      [dev]
jobs:
  update-deps-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Merge dev into deps branch
        uses: devmasx/merge-branch@1.4.0
        with:
          label_name: 'merged dev into deps'
          from_branch: 'dev'
          target_branch: 'deps'
          github_token: ${{ github.token }}